sudo: required 

services:
    - docker 
before_install:
    - docker build -t inc-abhijeet/docker-startup -f Dockerfile.dev .
script:
    - docker run -e CI=true inc-abhijeet/docker-startup npm run test:mwl:publish:always;
T
deploy:
    provider: elasticbeanstalk
    region: "ap-south-1"
    app: "docker_startup"
    env: "DockerStartup-env"
    bucket_name: "elasticbeanstalk-ap-south-1-517453957340"
    bucket_path: "docker_startup"
    on:
        branch: master
    access_key_id: $AWS_access_key
    secret_access_key:
        secure: "$AWS_secrate_value"
            
    








