sudo: required 

services:
    - docker 
before_install:
    - docker build -t inc-abhijeet/docker-startup -f Dockerfile.dev .
script:
    - docker run inc-abhijeet/docker-startup npm run test -- --coverage
    